version: "3.8"

services:
    # MongoDB Database
    mongodb:
        image: mongo:7.0
        container_name: focusflow-mongodb
        restart: unless-stopped
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
            MONGO_INITDB_DATABASE: focusflow
        volumes:
            - mongodb_data:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        networks:
            - focusflow-network

    # MongoDB Express (Optional - for database management)
    mongo-express:
        image: mongo-express:latest
        container_name: focusflow-mongo-express
        restart: unless-stopped
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
            ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD: password
        depends_on:
            - mongodb
        networks:
            - focusflow-network

    # Backend API
    backend:
        build:
            context: .
            target: development
        container_name: focusflow-backend
        restart: unless-stopped
        ports:
            - "5000:5000"
        environment:
            - NODE_ENV=development
            - PORT=5000
            - MONGODB_URI=mongodb://admin:password@mongodb:27017/focusflow?authSource=admin
            - JWT_SECRET=focusflow-dev-secret-key-change-in-production
            - JWT_EXPIRES_IN=7d
            - CORS_ORIGIN=http://localhost:3000
            - RATE_LIMIT_WINDOW_MS=900000
            - RATE_LIMIT_MAX_REQUESTS=100
            - BCRYPT_ROUNDS=12
        volumes:
            - .:/app
            - /app/node_modules
        depends_on:
            - mongodb
        networks:
            - focusflow-network
        command: npm run dev

volumes:
    mongodb_data:

networks:
    focusflow-network:
        driver: bridge
